//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodingCompare.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WinFormStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WinFormStrings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodingCompare.Resources.WinFormStrings", typeof(WinFormStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Address ähnelt.
        /// </summary>
        internal static string str_Adresse {
            get {
                return ResourceManager.GetString("str_Adresse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert Auto-Scan 1 here ähnelt.
        /// </summary>
        internal static string str_autoscan1 {
            get {
                return ResourceManager.GetString("str_autoscan1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert Auto-Scan 2 here ähnelt.
        /// </summary>
        internal static string str_autoscan2 {
            get {
                return ResourceManager.GetString("str_autoscan2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add two Autoscans to the Text-Boxes in the Autoscan Compare Tool ähnelt.
        /// </summary>
        internal static string str_autoscanNotSelected {
            get {
                return ResourceManager.GetString("str_autoscanNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto-Scans not valid ähnelt.
        /// </summary>
        internal static string str_autoscanNotValid {
            get {
                return ResourceManager.GetString("str_autoscanNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Windows Based VAG/VAS Emulator ähnelt.
        /// </summary>
        internal static string str_autoscanValidation_1 {
            get {
                return ResourceManager.GetString("str_autoscanValidation_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data version: ähnelt.
        /// </summary>
        internal static string str_autoscanValidation_2 {
            get {
                return ResourceManager.GetString("str_autoscanValidation_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die VIN:  ähnelt.
        /// </summary>
        internal static string str_autoscanValidation_3 {
            get {
                return ResourceManager.GetString("str_autoscanValidation_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die End- ähnelt.
        /// </summary>
        internal static string str_autoscanValidation_4 {
            get {
                return ResourceManager.GetString("str_autoscanValidation_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Chassis Type: ähnelt.
        /// </summary>
        internal static string str_autoscanValidation_5 {
            get {
                return ResourceManager.GetString("str_autoscanValidation_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No fault code found. ähnelt.
        /// </summary>
        internal static string str_autoscanValidation_6 {
            get {
                return ResourceManager.GetString("str_autoscanValidation_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Coding:  ähnelt.
        /// </summary>
        internal static string str_autoscanValidation_Codierung {
            get {
                return ResourceManager.GetString("str_autoscanValidation_Codierung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ende-------- ähnelt.
        /// </summary>
        internal static string str_autoscanValidation_End {
            get {
                return ResourceManager.GetString("str_autoscanValidation_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die License Plate ähnelt.
        /// </summary>
        internal static string str_autoscanValidation_licensePlate {
            get {
                return ResourceManager.GetString("str_autoscanValidation_licensePlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ^Address [0-9A-Z][0-9A-Z](?=\:) ähnelt.
        /// </summary>
        internal static string str_autoscanValidation_Regex {
            get {
                return ResourceManager.GetString("str_autoscanValidation_Regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Part No:  ähnelt.
        /// </summary>
        internal static string str_autoscanValidation_Teilenummer {
            get {
                return ResourceManager.GetString("str_autoscanValidation_Teilenummer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Part No SW:  ähnelt.
        /// </summary>
        internal static string str_autoscanValidation_TeilenummerSW {
            get {
                return ResourceManager.GetString("str_autoscanValidation_TeilenummerSW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Compare ähnelt.
        /// </summary>
        internal static string str_btnCompare {
            get {
                return ResourceManager.GetString("str_btnCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Coding 1 ähnelt.
        /// </summary>
        internal static string str_coding1 {
            get {
                return ResourceManager.GetString("str_coding1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Coding 2 ähnelt.
        /// </summary>
        internal static string str_coding2 {
            get {
                return ResourceManager.GetString("str_coding2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quick comparison ähnelt.
        /// </summary>
        internal static string str_CodingQuickCompare {
            get {
                return ResourceManager.GetString("str_CodingQuickCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Codings differ in length ähnelt.
        /// </summary>
        internal static string str_codingsNotSameLength {
            get {
                return ResourceManager.GetString("str_codingsNotSameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Compare results ähnelt.
        /// </summary>
        internal static string str_compareResults {
            get {
                return ResourceManager.GetString("str_compareResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto-Scan GUI context menue on/off ähnelt.
        /// </summary>
        internal static string str_contextMenue {
            get {
                return ResourceManager.GetString("str_contextMenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Context menue item &quot;Auto-Scan GUI&quot; added for TXT files ähnelt.
        /// </summary>
        internal static string str_contextMenue_Added {
            get {
                return ResourceManager.GetString("str_contextMenue_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Context menue item &quot;Auto-Scan GUI&quot; deleted for TXT files ähnelt.
        /// </summary>
        internal static string str_contextMenue_Deleted {
            get {
                return ResourceManager.GetString("str_contextMenue_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Operation failed. (Running as administrator?) ähnelt.
        /// </summary>
        internal static string str_ContextMenuError {
            get {
                return ResourceManager.GetString("str_ContextMenuError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy to clipboard ähnelt.
        /// </summary>
        internal static string str_copyClipboard {
            get {
                return ResourceManager.GetString("str_copyClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        internal static string str_Error {
            get {
                return ResourceManager.GetString("str_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No text file attached ähnelt.
        /// </summary>
        internal static string str_errorNoTextFile {
            get {
                return ResourceManager.GetString("str_errorNoTextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Information ähnelt.
        /// </summary>
        internal static string str_Hint {
            get {
                return ResourceManager.GetString("str_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ignore chassis type ähnelt.
        /// </summary>
        internal static string str_ignoreCarDerivate {
            get {
                return ResourceManager.GetString("str_ignoreCarDerivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ignore index ähnelt.
        /// </summary>
        internal static string str_ignoreIndex {
            get {
                return ResourceManager.GetString("str_ignoreIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Forum code ähnelt.
        /// </summary>
        internal static string str_lblCodeForum {
            get {
                return ResourceManager.GetString("str_lblCodeForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quick comparison of two codings ähnelt.
        /// </summary>
        internal static string str_lblDirectCompare {
            get {
                return ResourceManager.GetString("str_lblDirectCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LCode.exe could not be found / started ähnelt.
        /// </summary>
        internal static string str_LCodeError {
            get {
                return ResourceManager.GetString("str_LCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MY ähnelt.
        /// </summary>
        internal static string str_modelYear {
            get {
                return ResourceManager.GetString("str_modelYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No comparable units found or no differences in coding found ähnelt.
        /// </summary>
        internal static string str_noDifferencesFound {
            get {
                return ResourceManager.GetString("str_noDifferencesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die not supported ähnelt.
        /// </summary>
        internal static string str_notSupported {
            get {
                return ResourceManager.GetString("str_notSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die only differences ähnelt.
        /// </summary>
        internal static string str_onlyDifferences {
            get {
                return ResourceManager.GetString("str_onlyDifferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Right click to close ähnelt.
        /// </summary>
        internal static string str_rightClickToClose {
            get {
                return ResourceManager.GetString("str_rightClickToClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Address: ähnelt.
        /// </summary>
        internal static string str_searchCodingAdresse {
            get {
                return ResourceManager.GetString("str_searchCodingAdresse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Basepath... ähnelt.
        /// </summary>
        internal static string str_searchCodingBasePath {
            get {
                return ResourceManager.GetString("str_searchCodingBasePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bit set ähnelt.
        /// </summary>
        internal static string str_searchCodingBitSet {
            get {
                return ResourceManager.GetString("str_searchCodingBitSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search ähnelt.
        /// </summary>
        internal static string str_searchCodingButtonSearch {
            get {
                return ResourceManager.GetString("str_searchCodingButtonSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 0 hits ähnelt.
        /// </summary>
        internal static string str_searchCodingNoHits {
            get {
                return ResourceManager.GetString("str_searchCodingNoHits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search for coding: ähnelt.
        /// </summary>
        internal static string str_searchCodingTitle {
            get {
                return ResourceManager.GetString("str_searchCodingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erfolgreich ähnelt.
        /// </summary>
        internal static string str_Success {
            get {
                return ResourceManager.GetString("str_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die synchronous scrolling ähnelt.
        /// </summary>
        internal static string str_synchronousScrolling {
            get {
                return ResourceManager.GetString("str_synchronousScrolling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die C:\Ross-Tech\VCDS\ ähnelt.
        /// </summary>
        internal static string str_VCDSpath {
            get {
                return ResourceManager.GetString("str_VCDSpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die VCDS Autoscan coding compare (by VCDS.de) ähnelt.
        /// </summary>
        internal static string str_winformTitle {
            get {
                return ResourceManager.GetString("str_winformTitle", resourceCulture);
            }
        }
    }
}
